apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: flaskapp-pipeline
spec:
  resources:
    - name: source-repo
      type: git
    - name: flaskapp-image
      type: image
  tasks:
    - name: build-docker-image
      taskRef:
        name: build-docker-image-from-git-source
      params:
        - name: pathToDockerFile
          value: $(resources.inputs.docker-source.path)/Dockerfile
        - name: pathToContext
          value: $(resources.inputs.docker-source.path)
      resources:
        inputs:
          - name: docker-source
            resource: source-repo
        outputs:
          - name: builtImage
            resource: flaskapp-image
            #    - name: deploy
            #      runAfter: [build-docker-image]
            #      taskRef:
            #        name: deploy-kubectl
            #      resources:
            #        inputs:
            #          - name: source-repo
            #            resource: source-repo
