apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: flaskapp-git
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/rbalagopalakrishna/flaskapp
      #  secrets:
      #    - fieldName: authToken
      #      secretName: github-secrets
      #      secretKey: token
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: flaskapp-image
spec:
  type: image
  params:
    - name: url
      value: index.docker.io/balagopalraj/flaskapp:latest2
      #---
      #apiVersion: tekton.dev/v1alpha1
      #kind: PipelineResource
      #metadata:
      #  name: event-to-sink
      #spec:
      #  type: cloudEvent
      #  params:
      #  - name: targetURI
      #    value: http://sink:8080
